export enum APP_SETTINGS {
  POLICE_ENV = 'POLICE_ENV',
  POLICE_PORT = 'POLICE_PORT',
  POLICE_TG_API_ID = 'POLICE_TG_API_ID',
  POLICE_TG_API_HASH = 'POLICE_TG_API_HASH',
  POLICE_DB_HOST = 'POLICE_DB_HOST',
  POLICE_DB_PORT = 'POLICE_DB_PORT',
  POLICE_DB_USER = 'POLICE_DB_USER',
  POLICE_DB_PASSWORD = 'POLICE_DB_PASSWORD',
  POLICE_DB_NAME = 'POLICE_DB_NAME',
  POLICE_CLIENT_USER_ID = 'POLICE_CLIENT_USER_ID',
  POLICE_DEVOPS_USER_ID = 'POLICE_DEVOPS_USER_ID',
}
